USB_VID = 0x303a
USB_PID = 0x813F
USB_PRODUCT = "LILYGO T-DISPLAY S3 16MB Flash 8MB PSRAM"
USB_MANUFACTURER = "LILYGO"

IDF_TARGET = esp32s3

CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 16MB

OPTIMIZATION_FLAGS = -Os
CIRCUITPY_ESP32_CAMERA = 0
